services:
  - type: web
    name: connecteam-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: API_KEY
        sync: false  # Set this manually in the Render dashboard
